---
title: "Genetic and Environmental Impacts on Alzheimer's Disease Incidence"
subtitle: "Molecular Epidemiology Essay, Spring 2024"
author: "Savannah Hammerton"
format: 
   docx:
    citeproc: false
    filters:
      - at: pre-render
        path: "../../_extensions/andrewheiss/wordcount/citeproc.lua"
      - at: pre-render
        path: "../../_extensions/andrewheiss/wordcount/wordcount.lua"
csl: vancouver.csl
bibliography: essay.bib
---


# Introduction

Alzheimer's Disease (AD) was the sixth leading cause of death in the US in 2018, with an estimated 6 million diagnosed cases in 2017 expected to climb to anywhere from 14-15 million by 2016 [@matthews19; @nih23a; @robinson17]. It is clinically characterized by cognitive decline, loss of memory (primarily episodic memory), and a progressive loss in ability to carry out basic activities [@piaceri13; @nih23a; @tellechea18; @graff-radford21]. Physiologically, immunoreactive senile plaques (SP) (or, amyloid-$\beta$, A$\beta$, plaques) and immunoreactive neurofibrillary tangles (NFT, made of tau protein) have both been associated with AD [@killin16; @raulin22]. There are many genetic, environmental, and lifestyle factors that have been shown to be associated with the risk of developing AD, and these factors often interact with each other. Understanding how these factors impact risk independently and in interactions with each other can help identify who is at highest risk of AD as well as aid in developing targeted interventions to reduce that risk. This review will examine recent literature on risk factors of AD and how they interact with each other. 

# Risk factors of Alzheimer's Disease (AD)

Some of the most common and strongest associations with the development of AD are reported to be advanced age, female sex, and the presence or mutations of certain genes [@scheyer18; @riedel16; @raulin22; @dolgin22; @cacace16]. Some studies have reported the higher risk in females to be due to increased longevity, but others have refuted this and shown menopause to be a particular time in which chemical changes in the brain could lead to neurological dysfunction [@scheyer18; @riedel16]. There also appears to be an interaction between genetics and sex, where the presence of the _APOE4_ gene increases the likelihood of developing AD in females more than it does in males [@riedel16]. Other factors such as exposure to heavy and other metals, traumatic brain injury, malnutrition, obesity, type 2 diabetes, vascular disease, history of certain infectious diseases, chronic stress, and various other environmental exposures [@aarmstrong19; @killin16; @robinson17].

# Varying pathogenesis and classifications of Alzheimer's Disease (AD)

Alzheimer's Disease (AD) can be differentially described in regard to both the age of diagnosis and the general etiology (@tbl-types). There are two distinct types of Alzheimer's Disease (AD) based on diagnosis age: early-onset (EOAD), which is AD diagnosed in those younger than 65, and late-onset (LOAD), diagnosed in those 65 and older [@tellechea18; @piaceri13]. EOAD and LOAD appear to have very different etiologies, with LOAD having a particularly complex etiology that is related to combinations of factors, including genetic, environmental, and lifestyle characteristics that often interact with each other [@robinson17; @piaceri13]. 

AD can also be broken down into familial (FAD), a type related to mutations in three major genes, and sporadic, or a type related to a combination of genetic and environmental factors, Alzheimer's [@piaceri13]. FAD has been observed more commonly in early-onset cases but has also been seen in late-onset cases [@piaceri13; @robinson17]. Mutations in the _APP_, _PSEN1_, and _PSEN2_ genes are thought to be directly responsible for FAD and, therefore, for most EOAD cases [@nih23a; @khan20; @piaceri13]. However, FAD is very rare, making up only 5% of AD cases [@piaceri13]. The _APOE4_ gene has been shown to be associated more strongly with late-onset Alzheimer's disease (LOAD) [@khan20].

```{r}
#| echo: FALSE 
#| message: false
#| warning: false
#| label: tbl-types
#| tbl-cap: "Different types of Alzheimer's Disease as defined by age of onset/diagnosis and apparent source."
tibble::tribble(~Type, ~Definition, ~Factor,
                "Early-Onset Alzhheimer's Disease (EOAD)", " Alzheimer's Disease that presents/is diagnosed in those younger than 65", "Age",
                "Late-Onset Alzheimer's Disease (LOAD)", "Alzheimer's Disease that presents/is diagnosed in those 65 and older", "Age",
                "Family Alzheimer's Disease (FAD)", "Alzheimer's Disease related to specific genetic mutations and connected to family history (rare)", "Source",
                "Sporadic Alzheimer's Disease", "Alzheimer's Disease related to combination of genetic and environmental/lifestyle factors that does not appear inherited through family history", "Source") |> 
  gt::gt(groupname_col = "Factor") |> 
  gt::tab_options(table.layout = "auto") |> 
  gt::as_raw_html()
```


# What does the _APOE4_ gene do? 

The _APOE4_ gene is associated with impaired brain cholesterol transportation and processing, which the _APOE_ gene is partially responsible for [@dolgin22; @raulin22; @riedel16]. Some variants of the _APOE_ gene actually appear protective, like the _APOE2_ gene, which is also associated with increased life expectancy [@raulin22]. However, the presence of the _APOE4_ gene has been associated with anywhere from a 3-fold to a 15-fold increase in the development of Alzheimer's Disease (AD) [@riedel16; @dolgin22; @raulin22]. However, not all those with AD also have the _APOE4_ gene, and it is not the only gene associated with AD [@riedel16; @raulin22; @piaceri13].

# How do lifestyle and environment impact AD risk? 

The development of amyloid-$\beta$ (A$\beta$) plaques and neurofibrillary tangles (NFT, made of tau protein), both of which are pathological manifestations of Alzheimer's Disease (AD), can be impacted by several lifestyle and environmental factors. Adequate exercise, healthy diet, and good gut health are all associated with reduced A$\beta$ accumulation and toxicity, while poor sleep is associated with both A$\beta$ and tau accumulation [@raulin22; @khan20]. Healthy exercise and diet habits have also been shown to be protective against cognitive decline; meanwhile, vascular health conditions like hypertension and stroke have been shown to be associated with an increased risk of developing AD, and these conditions are made more likely by factors such as obesity and type 2 diabetes [@robinson17]. Other factors such as persistent infections like herpes simplex virus-1, depression, exposure to heavy metals, air pollution, and pesticides have been associated with varying amounts of increased risk of AD incidence [@killin16; @khan20; @aarmstrong19; @robinson17]. Overall, as with many other chronic health conditions, other chronic comorbidities, states, and exposures appear to play a large role in its development and progression. 

# What is the impact of genetics and the environment together? 

As with almost all health conditions and diseases, risk factors for Alzheimer's Disease (AD) do not act simply or independently on the likelihood of developing the disease. For instance, the impact of the _APOE4_ gene appears much stronger in females than in males [@riedel16]. Some environmental factors seem to interact with each other, as do some genetic factors [@aarmstrong19]. There are also interactions between environmental and genetic factors, such as the exposure to metals such as iron interacting with the _APOE4_ gene to increase risk of AD, education levels impacting age of AD onset in those with _PSEN1_ gene mutations, traumatic brain injuries increasing the risk of AD among those with the _APOE4_ gene, smoking history having a higher impact on the likelihood of AD in those with the _APOE4_ gene than in those without, and the _APOE4_ gene increasing the negative effects of poor diet and exercise habits on the likelihood of developing AD [@aarmstrong19; @migliore22; @dunn19]. There are also cases in which the interactions of genes and environment may benefit individuals at risk for AD; for example, some research has shown that increased education could counteract the increased risk of AD due to the _APOE4_ gene [@dunn19]. Future research may be aimed at identifying new genetic targets that impact the risk of AD incidence and examining those new and current genetic factors in combination with environmental factors to gain a fuller understanding of individuals' risks of AD and what may increase or decrease that risk. 

# Conclusion

Alzheimer's disease (AD) is a very strong example of gene-environment interactions. While an individual's genetics, lifestyle, and environment all play a powerful role on their likelihood of developing AD, the combination of these different factors together can drastically change their risk, for better or worse. Further research can focus on identifying further genetic targets for the identification and intervention of AD risk, as well as developing a better understanding of environmental impacts and their interaction with a person's genetics. 


\newpage

# References 

