---
title: "Molecular Epidemiology Midterm"
author: "Savannah Hammerton"
format: docx
---



```{r}
#| echo: FALSE
#| message: false
#| warning: false
dat <-  readRDS(here::here("data/processed-data/clean_dat.rds"))
```


<https://www.bv-brc.org/view/Taxonomy/11320?and(eq(host_group,Human),eq(isolation_country,%22USA%22),or(eq(collection_year,%222016%22),eq(collection_year,%222015%22),eq(collection_year,%222014%22),eq(collection_year,%222013%22),eq(collection_year,%222017%22)),or(eq(subtype,%22H1N1%22),eq(subtype,%22H3N2%22)),eq(genome_status,%22Complete%22),eq(segment,%224%22))#view_tab=genomes&filter=false> 

Filters:

  * Genome Status: Complete
  * Segment: 4
  * Subtype: H1N1, H3N2
  * Collection Year: 2013-2017
  * Isolation Country: USA
  * Host Group: Human
  
```{r}
#| echo: FALSE
#| message: false
#| warning: false
dat |> 
  dplyr::filter(subtype == "H1N1") |> 
  dplyr::select(host_gender, collection_year, age) |> 
  gtsummary::tbl_summary(by = collection_year)
```
  
```{r}
#| echo: FALSE 
#| message: false
#| warning: false
dat |> 
  dplyr::filter(subtype == "H3N2") |> 
  dplyr::select(host_gender, collection_year, age) |> 
  gtsummary::tbl_summary(by = collection_year)
```
  
  